import SuperNeoFormal.NumiSealEndToEnd

/-!
NumiSealZK simulation/privacy surface under explicit leakage.

The model used here is the standard simulation-style privacy shape: the verifier
view of a real proof must be indistinguishable from a view generated by a
simulator using only the declared leakage.  The leakage model is explicit and
does not include hardware side channels; those remain release/deployment
evidence obligations outside proof bytes.
-/

namespace SuperNeoFormal

structure NumiSealZKLeakageModel where
  publicStatementBound : Prop
  aggregateMetadataBound : Prop
  tensorDimensionsBound : Prop
  randomnessSessionIDPublic : Prop
  declaredLeakageDigestCanonical : Prop
  proofValidityPublic : Prop
  hardwareSideChannelsExcluded : Prop

def NumiSealZKLeakageModelAccepted
    (model : NumiSealZKLeakageModel) : Prop :=
  model.publicStatementBound
    ∧ model.aggregateMetadataBound
    ∧ model.tensorDimensionsBound
    ∧ model.randomnessSessionIDPublic
    ∧ model.declaredLeakageDigestCanonical
    ∧ model.proofValidityPublic
    ∧ model.hardwareSideChannelsExcluded

structure NumiSealZKSimulationPrivacyClaim
    (View Leakage : Type) where
  realView : View
  simulatedView : View
  declaredLeakage : Leakage
  leakageFunction : View → Leakage
  indistinguishable : View → View → Prop

def NumiSealZKSimulationPrivacyHolds
    {View Leakage : Type}
    (claim : NumiSealZKSimulationPrivacyClaim View Leakage) : Prop :=
  claim.leakageFunction claim.realView = claim.declaredLeakage
    ∧ claim.indistinguishable claim.realView claim.simulatedView

structure NumiSealZKPrivacyObligationStatus where
  leakageFunction : TheoremObligationStatus
  simulatorConstruction : TheoremObligationStatus
  randomnessFreshness : TheoremObligationStatus
  declaredLeakageDigest : TheoremObligationStatus
  hardwareSideChannelExclusion : TheoremObligationStatus

def NumiSealZKPrivacyObligationStatus.FullyInstantiated
    (status : NumiSealZKPrivacyObligationStatus) : Prop :=
  status.leakageFunction.Accepted
    ∧ status.simulatorConstruction.Accepted
    ∧ status.randomnessFreshness.Accepted
    ∧ status.declaredLeakageDigest.Accepted
    ∧ status.hardwareSideChannelExclusion.Accepted

structure NumiSealZKSimulationEvidence
    {View Leakage : Type}
    (zk : NumiSealZKGates)
    (model : NumiSealZKLeakageModel)
    (claim : NumiSealZKSimulationPrivacyClaim View Leakage) where
  leakageSound :
    NumiSealZKAccepted zk →
      NumiSealZKLeakageModelAccepted model →
        claim.leakageFunction claim.realView = claim.declaredLeakage
  simulatorSound :
    NumiSealZKAccepted zk →
      NumiSealZKLeakageModelAccepted model →
        claim.indistinguishable claim.realView claim.simulatedView

theorem numiSealZKSimulationPrivacy_from_evidence
    {View Leakage : Type}
    {zk : NumiSealZKGates}
    {model : NumiSealZKLeakageModel}
    {claim : NumiSealZKSimulationPrivacyClaim View Leakage}
    (hZK : NumiSealZKAccepted zk)
    (hModel : NumiSealZKLeakageModelAccepted model)
    (evidence : NumiSealZKSimulationEvidence zk model claim) :
    NumiSealZKSimulationPrivacyHolds claim :=
  ⟨
    evidence.leakageSound hZK hModel,
    evidence.simulatorSound hZK hModel
  ⟩

theorem numiSealZKProduct_privacy_from_product_acceptance
    {View Leakage : Type}
    {gates : NumiSealProductVerifierGates}
    {model : NumiSealZKLeakageModel}
    {claim : NumiSealZKSimulationPrivacyClaim View Leakage}
    (hAccepts : NumiSealZKProductVerifierAccepts gates)
    (hModel : NumiSealZKLeakageModelAccepted model)
    (evidence : NumiSealZKSimulationEvidence gates.zk model claim) :
    NumiSealZKSimulationPrivacyHolds claim := by
  exact
    numiSealZKSimulationPrivacy_from_evidence
      (numiSealProduct_acceptance_requires_zk_layer hAccepts.1)
      hModel
      evidence

theorem numiSealZKPrivacy_leakage_only_view
    {View Leakage : Type}
    {claim : NumiSealZKSimulationPrivacyClaim View Leakage}
    (hPrivacy : NumiSealZKSimulationPrivacyHolds claim) :
    claim.leakageFunction claim.realView = claim.declaredLeakage :=
  hPrivacy.1

theorem numiSealZKPrivacy_simulated_view_indistinguishable
    {View Leakage : Type}
    {claim : NumiSealZKSimulationPrivacyClaim View Leakage}
    (hPrivacy : NumiSealZKSimulationPrivacyHolds claim) :
    claim.indistinguishable claim.realView claim.simulatedView :=
  hPrivacy.2

end SuperNeoFormal
